package io.github.xgl34222220.bichen;

import android.app.*;
import android.content.*;
import android.content.pm.*;
import android.content.res.ColorStateList;
import android.content.res.Configuration;
import android.graphics.*;
import android.graphics.drawable.*;
import android.net.VpnService;
import android.os.*;
import android.provider.Settings;
import android.text.*;
import android.view.*;
import android.view.inputmethod.InputMethodManager;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.text.*;
import java.util.*;
import java.util.concurrent.*;

/** Native phone UI. The window is built once; work and list updates never recreate it. */
public final class MainActivity extends Activity {
    private static final int VPN_REQUEST=40, EXPORT=41, IMPORT=42;
    private final ExecutorService worker=Executors.newSingleThreadExecutor();
    private final Handler ui=new Handler(Looper.getMainLooper());
    private final ArrayList<AppEntry> apps=new ArrayList<>();
    private SharedPreferences prefs;
    private RuleStore rules;
    private volatile JSONObject status=new JSONObject();
    private LinearLayout shell, body, nav, banner;
    private FrameLayout content;
    private ScrollView scroll;
    private ProgressBar progress;
    private TextView heading, subtitle, feedback, appsPending, appsApply, appEmpty, queryMetric, blockMetric, errorMetric;
    private AppAdapter appAdapter;
    private LogAdapter logAdapter;
    private ListView logList;
    private int tab=0, BG,TEXT,MUTED,ACCENT,SURFACE,SOFT,LINE,ERROR;
    private boolean busy=false, destroyed=false, appsLoaded=false, appsLoading=false, dark, systemApps=false, selectedOnly=false;
    private String notice="", pendingExport="", exportText="", appSearch="", logSearch="", busyLabel="";
    private boolean statusLoaded=false, homeRefreshNeeded=false;
    private String bundledModuleVersion="";
    private String queuedDocumentUri="", queuedDocumentKind="", queuedDocumentText="";
    private int queuedDocumentRequest=0;
    private final SharedPreferences.OnSharedPreferenceChangeListener preferenceListener=(p,key)->{
        if("dnsNetworkState".equals(key)||"dnsNetworkReportError".equals(key)||"dailyUpdateRunning".equals(key)||"dailyUpdateError".equals(key)||"dailyUpdateLastSuccess".equals(key)||"dnsLogs".equals(key)||"activeBypassApps".equals(key)||"vpnError".equals(key)||"vpnWanted".equals(key)||"blocked".equals(key)||"queries".equals(key)||"errors".equals(key)) {
            if(!"dnsLogs".equals(key))homeRefreshNeeded=true;
            ui.removeCallbacks(this.refreshLive); ui.postDelayed(this.refreshLive,180);
        }
    };
    private final Runnable refreshLive=()->{
        if(destroyed)return;
        if(homeRefreshNeeded&&tab==0)showPage(true);homeRefreshNeeded=false;
        if(tab==1)updatePending();
        if(tab==3&&logAdapter!=null){logAdapter.refresh();if(queryMetric!=null)queryMetric.setText(format(prefs.getLong("queries",0)));if(blockMetric!=null)blockMetric.setText(format(prefs.getLong("blocked",0)));if(errorMetric!=null)errorMetric.setText(format(prefs.getLong("errors",0)));}
    };
    private interface Job { String run() throws Exception; }
    private interface Flag { void changed(boolean on); }
    private static final class AppEntry {
        final ApplicationInfo info; final String label; final Bitmap icon;
        AppEntry(ApplicationInfo i,String l,Bitmap b){info=i;label=l;icon=b;}
    }
    @Override public void onCreate(Bundle state) {
        prefs=getSharedPreferences("bichen",MODE_PRIVATE);
        dark=useDark();setTheme(dark?R.style.AppThemeDark:R.style.AppTheme);
        super.onCreate(state); palette();
        if(state!=null){tab=state.getInt("tab",0);appSearch=state.getString("appSearch","");logSearch=state.getString("logSearch","");systemApps=state.getBoolean("systemApps");selectedOnly=state.getBoolean("selectedOnly");pendingExport=state.getString("pendingExport","");exportText=state.getString("exportText","");queuedDocumentUri=state.getString("queuedDocumentUri","");queuedDocumentKind=state.getString("queuedDocumentKind","");queuedDocumentText=state.getString("queuedDocumentText","");queuedDocumentRequest=state.getInt("queuedDocumentRequest",0);}
        buildWindow();showPage(false);prefs.registerOnSharedPreferenceChangeListener(preferenceListener);
        loadStatus();
    }
    @Override public void onSaveInstanceState(Bundle b){super.onSaveInstanceState(b);b.putInt("tab",tab);b.putString("appSearch",appSearch);b.putString("logSearch",logSearch);b.putBoolean("systemApps",systemApps);b.putBoolean("selectedOnly",selectedOnly);b.putString("pendingExport",pendingExport);b.putString("exportText",exportText);b.putString("queuedDocumentUri",queuedDocumentUri);b.putString("queuedDocumentKind",queuedDocumentKind);b.putString("queuedDocumentText",queuedDocumentText);b.putInt("queuedDocumentRequest",queuedDocumentRequest);}
    @Override public void onResume(){super.onResume();if(prefs!=null){if(useDark()!=dark){recreate();return;}String e=prefs.getString("vpnError","");if(!e.isEmpty()){notice=e;updateBanner();}ui.post(refreshLive);}}
    @Override public void onDestroy(){destroyed=true;prefs.unregisterOnSharedPreferenceChangeListener(preferenceListener);ui.removeCallbacksAndMessages(null);worker.shutdown();super.onDestroy();}
    private boolean useDark(){String mode=prefs.getString("appearance","system");return mode.equals("dark")||(mode.equals("system")&&(getResources().getConfiguration().uiMode&Configuration.UI_MODE_NIGHT_MASK)==Configuration.UI_MODE_NIGHT_YES);}
    private void palette(){BG=dark?0xff121714:0xfff4f5f2;TEXT=dark?0xffe6eee8:0xff22342b;MUTED=dark?0xff9aa99f:0xff78867d;ACCENT=dark?0xff8dd3c3:0xff317c70;SURFACE=dark?0xff1d2721:0xfffefefd;SOFT=dark?0xff283930:0xffe8efea;LINE=dark?0xff324036:0xffe9eeea;ERROR=dark?0xffffb6a0:0xffac5d45;}
    private int dp(float n){return Math.round(n*getResources().getDisplayMetrics().density);}
    private GradientDrawable background(int color,float radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));return g;}
    private Drawable tappable(int color,float radius){return new RippleDrawable(ColorStateList.valueOf(dark?0x228dd3c3:0x18317c70),background(color,radius),background(Color.WHITE,radius));}
    private LinearLayout column(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}
    private LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setGravity(Gravity.CENTER_VERTICAL);return l;}
    private TextView text(String s,float size,int color,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setFontFeatureSettings("kern");t.setIncludeFontPadding(false);t.setLineSpacing(dp(3),1);if(bold)t.setTypeface(Typeface.create("sans-serif-medium",Typeface.NORMAL));return t;}
    private void gap(LinearLayout l,int height){l.addView(new View(this),new LinearLayout.LayoutParams(1,dp(height)));}
    private void pad(View v,int n){v.setPadding(dp(n),dp(n),dp(n),dp(n));}
    private void divider(LinearLayout l){View line=new View(this);line.setBackgroundColor(LINE);l.addView(line,new LinearLayout.LayoutParams(-1,dp(1)));}
    private void action(Runnable r){if(busy){Toast.makeText(this,busyLabel+"，请稍候",Toast.LENGTH_SHORT).show();return;}r.run();}
    private TextView button(String label,boolean primary,Runnable runnable){TextView t=text(label,14,primary?(dark?0xff163b31:Color.WHITE):ACCENT,true);t.setGravity(Gravity.CENTER);t.setPadding(dp(15),dp(14),dp(15),dp(14));t.setMinHeight(dp(48));t.setBackground(tappable(primary?ACCENT:SOFT,17));t.setOnClickListener(v->action(runnable));return t;}
    private void addButton(LinearLayout l,String label,boolean primary,Runnable runnable){gap(l,12);l.addView(button(label,primary,runnable),new LinearLayout.LayoutParams(-1,-2));}
    private View iconButton(String icon,String description,Runnable click){FrameLayout f=new FrameLayout(this);f.setBackground(tappable(SURFACE,23));f.setElevation(dp(1));IconView i=new IconView(this,icon,TEXT);FrameLayout.LayoutParams ip=new FrameLayout.LayoutParams(dp(21),dp(21),Gravity.CENTER);f.addView(i,ip);f.setContentDescription(description);f.setOnClickListener(v->action(click));f.setLayoutParams(new LinearLayout.LayoutParams(dp(44),dp(44)));return f;}
    private LinearLayout card(LinearLayout parent){LinearLayout c=column();pad(c,20);GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{SURFACE,dark?0xff202c24:0xfffafcf9});g.setCornerRadius(dp(24));c.setBackground(g);c.setElevation(dp(dark?0:1.4f));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(14);parent.addView(c,p);return c;}
    private LinearLayout card(String title,String description){LinearLayout c=card(body);if(title!=null)c.addView(text(title,17,TEXT,true));if(description!=null){gap(c,8);c.addView(text(description,12,MUTED,false));}return c;}
    private void section(String title){TextView t=text(title,13,MUTED,true);t.setPadding(dp(5),dp(5),0,dp(12));body.addView(t);}
    private LinearLayout actionRow(LinearLayout parent,String icon,String title,String description,Runnable runnable){LinearLayout r=row();r.setPadding(0,dp(13),0,dp(13));r.setMinimumHeight(dp(58));r.setBackground(tappable(Color.TRANSPARENT,12));IconView i=new IconView(this,icon,ACCENT);r.addView(i,new LinearLayout.LayoutParams(dp(23),dp(23)));LinearLayout labels=column();labels.setPadding(dp(13),0,dp(9),0);labels.addView(text(title,14,TEXT,true));if(description!=null&&!description.isEmpty()){gap(labels,5);labels.addView(text(description,11,MUTED,false));}r.addView(labels,new LinearLayout.LayoutParams(0,-2,1));r.addView(new IconView(this,"chevron",MUTED),new LinearLayout.LayoutParams(dp(16),dp(16)));r.setOnClickListener(v->action(runnable));parent.addView(r,new LinearLayout.LayoutParams(-1,-2));return r;}
    private void buildWindow(){
        shell=column();shell.setBackgroundColor(BG);shell.setClipChildren(false);
        shell.setOnApplyWindowInsetsListener((v,insets)->{v.setPadding(insets.getSystemWindowInsetLeft(),insets.getSystemWindowInsetTop(),insets.getSystemWindowInsetRight(),insets.getSystemWindowInsetBottom());return insets.consumeSystemWindowInsets();});
        getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);
        getWindow().getDecorView().setSystemUiVisibility(dark?0:View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR);
        LinearLayout header=row();header.setPadding(dp(23),dp(17),dp(21),dp(17));LinearLayout labels=column();heading=text("辟尘",29,TEXT,true);labels.addView(heading);gap(labels,7);subtitle=text("少一点打扰，多一点清净",12,MUTED,false);labels.addView(subtitle);header.addView(labels,new LinearLayout.LayoutParams(0,-2,1));header.addView(iconButton("settings","设置与诊断",this::showSettings));shell.addView(header);
        progress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);progress.setIndeterminate(true);progress.setIndeterminateTintList(ColorStateList.valueOf(ACCENT));progress.setVisibility(View.GONE);shell.addView(progress,new LinearLayout.LayoutParams(-1,dp(3)));
        banner=row();banner.setPadding(dp(15),dp(11),dp(8),dp(11));banner.setBackground(background(SOFT,17));feedback=text("",12,ACCENT,false);feedback.setMaxLines(3);feedback.setEllipsize(TextUtils.TruncateAt.END);feedback.setOnClickListener(v->showLong("操作结果",notice));banner.addView(feedback,new LinearLayout.LayoutParams(0,-2,1));TextView close=text("×",23,MUTED,false);close.setGravity(Gravity.CENTER);close.setContentDescription("收起提示");close.setOnClickListener(v->{notice="";updateBanner();});banner.addView(close,new LinearLayout.LayoutParams(dp(36),dp(36)));LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,-2);bp.setMargins(dp(19),0,dp(19),dp(12));shell.addView(banner,bp);
        content=new FrameLayout(this);shell.addView(content,new LinearLayout.LayoutParams(-1,0,1));
        nav=row();nav.setPadding(dp(7),dp(6),dp(7),dp(6));nav.setBackground(new GradientDrawable(GradientDrawable.Orientation.TOP_BOTTOM,new int[]{dark?0xff2b3830:0xfffefffd,dark?0xff1e2922:0xffedf3ed}));nav.getBackground().setAlpha(245);((GradientDrawable)nav.getBackground()).setCornerRadius(dp(29));nav.setElevation(dp(8));LinearLayout.LayoutParams np=new LinearLayout.LayoutParams(-1,dp(70));np.setMargins(dp(24),dp(8),dp(24),dp(12));shell.addView(nav,np);
        setContentView(shell);updateBanner();renderNav();
    }
    private void renderNav(){nav.removeAllViews();String[] labels={"保护","应用","规则","活动"},icons={"shield","apps","rules","activity"};for(int n=0;n<4;n++){final int selected=n;LinearLayout item=column();item.setGravity(Gravity.CENTER);item.setBackground(tappable(n==tab?SOFT:Color.TRANSPARENT,22));item.addView(new IconView(this,icons[n],n==tab?ACCENT:MUTED),new LinearLayout.LayoutParams(dp(22),dp(22)));gap(item,5);item.addView(text(labels[n],11,n==tab?ACCENT:MUTED,n==tab));item.setContentDescription(labels[n]);item.setSelected(n==tab);item.setOnClickListener(v->{if(tab==selected)return;((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(content.getWindowToken(),0);tab=selected;showPage(false);renderNav();});nav.addView(item,new LinearLayout.LayoutParams(0,-1,1));}}
    private void showPage(boolean preserve){if(destroyed)return;int oldY=preserve&&scroll!=null?scroll.getScrollY():0;content.removeAllViews();scroll=null;appAdapter=null;logAdapter=null;logList=null;appsPending=null;appsApply=null;heading.setText(new String[]{"辟尘","应用放行","过滤规则","请求活动"}[tab]);subtitle.setText(new String[]{"少一点打扰，多一点清净","把选择权交还给你","来源、例外与每一次变化","保护发生了什么，一眼看清"}[tab]);
        if(tab==1){applicationPage();return;}if(tab==3){activityPage();return;}
        scroll=new ScrollView(this);scroll.setClipToPadding(false);scroll.setFillViewport(true);scroll.setVerticalScrollBarEnabled(false);body=column();body.setPadding(dp(19),dp(3),dp(19),dp(10));scroll.addView(body);content.addView(scroll,new FrameLayout.LayoutParams(-1,-1));if(tab==0)home();else rulePage();if(preserve){ScrollView s=scroll;s.post(()->s.scrollTo(0,oldY));}
    }
    private void updateBanner(){if(feedback==null)return;progress.setVisibility(busy?View.VISIBLE:View.GONE);banner.setVisibility(notice.isEmpty()&&!busy?View.GONE:View.VISIBLE);feedback.setText(busy?busyLabel+"…":notice);}
    private boolean installed(){return status.optBoolean("installed",false);}
    private boolean modern(){return status.optString("capabilities").contains("export-domains");}
    private boolean vpn(){return DnsVpnService.running;}
    private boolean vpnEngaged(){return vpn()||prefs.getBoolean("vpnWanted",false)||prefs.getBoolean("vpnRestoreHosts",false);}
    private boolean protectedNow(){return vpn()||(status.optBoolean("enabled")&&status.optBoolean("mounted"));}
    private String mode(){return vpnEngaged()?"vpn":prefs.getString("preferredMode","module");}
    private boolean ruleTarget()throws IOException{if(pendingReboot())throw new IOException("模块更新等待重启，请先重启手机。");if(!status.optBoolean("ok",false)||!status.has("installed"))throw new IOException("尚未确认模块状态，请刷新并完成 Root 授权。");if(installed()&&!modern())throw new IOException("请先安装内置新版模块并重启，再修改规则。");return installed();}
    private void home(){
        boolean active=protectedNow();LinearLayout hero=card(body);hero.setPadding(dp(23),dp(25),dp(23),dp(24));GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{dark?0xff233f34:0xffdeeee3,dark?0xff1f3128:0xfff5f3e6});g.setCornerRadius(dp(28));hero.setBackground(g);
        LinearLayout top=row();TextView eyebrow=text(active?"正在守护":"你的数字生活",12,ACCENT,true);top.addView(eyebrow,new LinearLayout.LayoutParams(0,-2,1));TextView modeChip=text(mode().equals("vpn")?"应用保护":"模块保护",11,ACCENT,true);modeChip.setPadding(dp(11),dp(7),dp(11),dp(7));modeChip.setBackground(tappable(dark?0xff354e40:0xfff6faf5,18));modeChip.setOnClickListener(v->action(this::showModePicker));top.addView(modeChip);hero.addView(top);gap(hero,22);
        LinearLayout state=row();LinearLayout name=column();name.addView(text(active?"保护已开启":vpnEngaged()?"保护正在切换":statusLoaded?"保护未开启":"正在检查状态",27,TEXT,true));gap(name,10);String detail=vpn()?networkSummary()+" · "+prefs.getInt("activeBypassCount",0)+" 个应用放行":active?"系统 hosts 已验证生效":!statusLoaded?"请完成 Root 授权，稍候查看结果":installed()?(status.optBoolean("enabled")?"规则已启用，实际挂载尚未验证":"随时开启，恢复清净日常"):"安装内置模块，开启系统保护";TextView desc=text(detail,12,MUTED,false);name.addView(desc);state.addView(name,new LinearLayout.LayoutParams(0,-2,1));FrameLayout power=new FrameLayout(this);power.setBackground(tappable(active?ACCENT:SURFACE,32));power.setElevation(dp(4));power.addView(new IconView(this,"power",active?(dark?0xff163b31:Color.WHITE):ACCENT),new FrameLayout.LayoutParams(dp(29),dp(29),Gravity.CENTER));power.setContentDescription(active?"停止保护":"开启保护");power.setOnClickListener(v->action(this::toggleProtection));LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(dp(64),dp(64));pp.leftMargin=dp(12);state.addView(power,pp);hero.addView(state);gap(hero,27);
        divider(hero);gap(hero,20);LinearLayout metrics=row();metric(metrics,format(rules==null?0:vpn()?rules.count():status.optInt("ruleCount")),"有效过滤规则");metric(metrics,vpn()?format(prefs.getLong("blocked",0)):bytes(status.optLong("hostsBytes")),vpn()?"累计 DNS 拦截":"规则文件大小");hero.addView(metrics);
        if(status.has("error")||!status.optBoolean("ok",true)){LinearLayout warning=card("需要处理",status.optString("error",status.optString("message","模块状态检查未成功")));actionRow(warning,"refresh","重新检查","完成 Root 授权后再试",this::loadStatus);}
        section("保护概览");LinearLayout overview=card(null,null);actionRow(overview,"module",installed()?"模块已安装 · "+status.optString("version","未知版本"):"安装辟尘模块",installed()?(status.optBoolean("mounted")?"挂载已验证 · ":"挂载未验证 · ")+bytes(status.optLong("storageBytes"))+" 数据占用":"App 已内置安装包，无需另外下载",this::showModuleManager);divider(overview);actionRow(overview,"rules","规则与更新",updateSummary(),()->{tab=2;showPage(false);renderNav();});divider(overview);actionRow(overview,"search","遇到误拦？","检查域名，或从请求记录一键放行",this::showTroubleshooter);
        LinearLayout hint=card(null,null);hint.addView(text(vpn()?"应用保护使用系统 VPN 槽位。打开其他 VPN 前，请先停止辟尘应用保护。":"模块保护不占 VPN，按域名拦截广告与追踪。需要按应用放行时，可切换到应用保护。",12,MUTED,false));actionRow(hint,"shield","切换保护方式",mode().equals("vpn")?"当前选择：应用保护":"当前选择：模块保护",this::showModePicker);
    }
    private TextView metric(LinearLayout p,String value,String label){LinearLayout c=column();TextView number=text(value,23,TEXT,true);c.addView(number);gap(c,7);c.addView(text(label,11,MUTED,false));p.addView(c,new LinearLayout.LayoutParams(0,-2,1));return number;}
    private String updateSummary(){if(prefs.getBoolean("dailyUpdateRunning",false))return "规则正在后台更新";String error=prefs.getString("dailyUpdateError","");if(!error.isEmpty())return "自动更新遇到问题，点此查看";long t=prefs.getLong("dailyUpdateLastSuccess",0);if(t==0)t=status.optLong("updatedAt",0)*1000;long checked=prefs.getLong("last_rule_check",0);if(checked>0)return "最近检查 "+date(checked)+" · 无变化时保留原规则";return t>0?"最近更新 "+date(t):"内置规则可离线使用";}
    private void toggleProtection(){if(vpnEngaged()){stopVpn();return;}if(protectedNow()){rootCommand("pause");return;}if(mode().equals("vpn"))prepareVpn();else if(!installed())showModuleManager();else rootCommand("enable");}
    private void showModePicker(){LinearLayout c=column();c.addView(text("选择保护方式",22,TEXT,true));gap(c,10);c.addView(text("两种方式互斥。应用保护支持单独放行，但会使用系统 VPN 槽位。",13,MUTED,false));final Dialog d=sheet(c);actionRow(c,"module","模块保护","不占 VPN · 所有应用共用域名规则",()->{d.dismiss();if(vpnEngaged()){new AlertDialog.Builder(this).setTitle("切回模块保护？").setMessage("将先停止应用保护并恢复原模块状态；恢复完成后可开启模块保护。").setNegativeButton("取消",null).setPositiveButton("切换",(a,b)->{prefs.edit().putString("preferredMode","module").apply();stopVpn();}).show();}else{prefs.edit().putString("preferredMode","module").apply();showPage(true);}});divider(c);actionRow(c,"apps","应用保护","本地 DNS VPN · 支持按应用放行",()->{d.dismiss();prepareVpn();});}
    private String networkSummary(){
        if(!vpn())return "应用保护未运行";
        String state=prefs.getString("dnsNetworkState","waiting");
        if("ready".equals(state))return "上游网络已连接，DNS 引擎运行中";
        if("blocked".equals(state))return "系统限制上游联网，保留本地过滤";
        return "等待网络恢复，保留本地过滤";
    }
    private void showModuleManager(){LinearLayout c=column();c.addView(text("模块管理",22,TEXT,true));gap(c,10);c.addView(text("App 版本："+version()+"\n内置模块："+(bundledModuleVersion.isEmpty()?"等待校验":bundledModuleVersion)+"\n安装 APK 是安装管理界面；Root 模块只从下方安装或导出。源码包不能刷入。",13,MUTED,false));final Dialog d=sheet(c);addButton(c,installed()?"安装内置模块更新":"安装内置模块",true,()->{d.dismiss();work("安装模块",()->{RootBridge.Result r=ModuleInstaller.install(this);if(r.code!=0)throw new IOException("安装失败（"+r.code+"）：\n"+r.output);return r.output;},this::loadStatus);});actionRow(c,"download","导出模块 ZIP","只导出已校验的模块，不含源码或 APK",()->{d.dismiss();exportFile("module");});divider(c);actionRow(c,"refresh","重新应用当前规则","修复当前模块挂载",()->{d.dismiss();rootCommand("apply");});divider(c);actionRow(c,"info","检查安装与挂载","查看真实诊断结果",()->{d.dismiss();runDiagnostics();});}
    private void applicationPage(){LinearLayout page=column();page.setPadding(dp(19),dp(3),dp(19),0);content.addView(page,new FrameLayout.LayoutParams(-1,-1));LinearLayout intro=card(page);intro.setPadding(dp(17),dp(15),dp(17),dp(15));LinearLayout top=row();LinearLayout labels=column();labels.addView(text("选中的应用直接放行",16,TEXT,true));gap(labels,7);appsPending=text("",12,MUTED,false);labels.addView(appsPending);top.addView(labels,new LinearLayout.LayoutParams(0,-2,1));appsApply=button(vpn()?"应用更改":"开启保护",true,()->{if(vpn())restartVpn();else prepareVpn();});LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-2,-2);ap.leftMargin=dp(10);top.addView(appsApply,ap);intro.addView(top);gap(intro,10);intro.addView(text("仅应用保护生效；会占用 VPN。勾选后需点击应用更改。",11,MUTED,false));
        EditText search=input("搜索名称或包名");search.setText(appSearch);page.addView(search);watch(search,s->{appSearch=s;if(appAdapter!=null)appAdapter.filter();});
        LinearLayout filter=row();CheckBox sys=check("系统应用",systemApps);sys.setOnCheckedChangeListener((b,on)->{systemApps=on;appAdapter.filter();});filter.addView(sys,new LinearLayout.LayoutParams(0,dp(43),1));CheckBox selected=check("只看已选择",selectedOnly);selected.setOnCheckedChangeListener((b,on)->{selectedOnly=on;appAdapter.filter();});filter.addView(selected,new LinearLayout.LayoutParams(0,dp(43),1));page.addView(filter);
        ListView list=new ListView(this);list.setDivider(new ColorDrawable(LINE));list.setDividerHeight(dp(1));list.setClipToPadding(false);list.setPadding(dp(13),0,dp(9),dp(5));list.setBackground(background(SURFACE,22));list.setVerticalScrollBarEnabled(false);appEmpty=emptyView(page,"正在读取应用…");list.setEmptyView(appEmpty);appAdapter=new AppAdapter();list.setAdapter(appAdapter);page.addView(list,new LinearLayout.LayoutParams(-1,0,1));appAdapter.filter();updatePending();if(!appsLoaded&&!appsLoading)loadApps();}
    private TextView emptyView(LinearLayout page,String label){TextView t=text(label,13,MUTED,false);t.setGravity(Gravity.CENTER);t.setPadding(0,dp(25),0,dp(25));page.addView(t,new LinearLayout.LayoutParams(-1,-2));return t;}
    private void updatePending(){if(appsPending==null)return;Set<String> draft=prefs.getStringSet("bypassApps",Collections.emptySet());Set<String> applied=prefs.getStringSet("activeBypassApps",Collections.emptySet());boolean dirty=vpn()&&!draft.equals(applied);appsPending.setText(dirty?"有未应用更改 · 已选 "+draft.size()+" 个":vpn()?"已应用 · "+prefs.getInt("activeBypassCount",0)+" 个应用放行":"已保存 "+draft.size()+" 个，开启后生效");appsPending.setTextColor(dirty?ERROR:MUTED);appsApply.setText(vpn()?"应用更改":"开启保护");}
    private CheckBox check(String label,boolean value){CheckBox c=new CheckBox(this);c.setText(label);c.setTextSize(12);c.setTextColor(MUTED);c.setButtonTintList(ColorStateList.valueOf(ACCENT));c.setChecked(value);return c;}
    private void loadApps(){appsLoading=true;worker.execute(()->{ArrayList<AppEntry> found=new ArrayList<>();String error="";try{PackageManager pm=getPackageManager();int size=dp(42);for(ApplicationInfo info:pm.getInstalledApplications(0)){if(info.packageName.equals(getPackageName()))continue;Bitmap bitmap=null;try{Drawable drawable=pm.getApplicationIcon(info);bitmap=Bitmap.createBitmap(size,size,Bitmap.Config.ARGB_8888);Canvas canvas=new Canvas(bitmap);drawable.setBounds(0,0,size,size);drawable.draw(canvas);}catch(Exception ignored){}found.add(new AppEntry(info,pm.getApplicationLabel(info).toString(),bitmap));}Collator order=Collator.getInstance(Locale.CHINA);found.sort((a,b)->order.compare(a.label,b.label));}catch(Exception e){error=e.getMessage();}final String failure=error;ui.post(()->{if(destroyed)return;appsLoading=false;appsLoaded=true;apps.clear();apps.addAll(found);if(appAdapter!=null)appAdapter.filter();if(!failure.isEmpty())message("读取应用失败："+failure);});});}
    private final class AppAdapter extends BaseAdapter {
        final ArrayList<AppEntry> shown=new ArrayList<>();
        void filter(){shown.clear();Set<String> selected=prefs.getStringSet("bypassApps",Collections.emptySet());String q=appSearch.toLowerCase(Locale.ROOT).trim();for(AppEntry a:apps){boolean chosen=selected.contains(a.info.packageName);if(selectedOnly&&!chosen)continue;if(!systemApps&&(a.info.flags&ApplicationInfo.FLAG_SYSTEM)!=0&&!chosen)continue;if(!a.label.toLowerCase(Locale.ROOT).contains(q)&&!a.info.packageName.toLowerCase(Locale.ROOT).contains(q))continue;shown.add(a);}if(appEmpty!=null)appEmpty.setText(appsLoaded?"没有匹配的应用":"正在读取应用…");notifyDataSetChanged();}
        public int getCount(){return shown.size();}public Object getItem(int n){return shown.get(n);}public long getItemId(int n){return n;}
        public View getView(int n,View convert,ViewGroup parent){AppHolder h;if(convert==null){h=new AppHolder();LinearLayout r=row();r.setPadding(0,dp(13),0,dp(13));h.icon=new ImageView(MainActivity.this);r.addView(h.icon,new LinearLayout.LayoutParams(dp(41),dp(41)));LinearLayout labels=column();labels.setPadding(dp(12),0,dp(8),0);h.name=text("",14,TEXT,true);h.name.setMaxLines(1);h.name.setEllipsize(TextUtils.TruncateAt.END);labels.addView(h.name);gap(labels,5);h.pkg=text("",10,MUTED,false);h.pkg.setSingleLine(true);h.pkg.setEllipsize(TextUtils.TruncateAt.MIDDLE);labels.addView(h.pkg);r.addView(labels,new LinearLayout.LayoutParams(0,-2,1));h.check=check("",false);h.check.setFocusable(false);r.addView(h.check,new LinearLayout.LayoutParams(dp(43),dp(43)));r.setTag(h);convert=r;}else h=(AppHolder)convert.getTag();AppEntry a=shown.get(n);h.name.setText(a.label);h.pkg.setText(a.info.packageName);h.icon.setImageBitmap(a.icon);h.check.setOnCheckedChangeListener(null);h.check.setChecked(prefs.getStringSet("bypassApps",Collections.emptySet()).contains(a.info.packageName));h.check.setContentDescription("放行 "+a.label);h.check.setOnCheckedChangeListener((b,on)->{HashSet<String> set=new HashSet<>(prefs.getStringSet("bypassApps",Collections.emptySet()));if(on)set.add(a.info.packageName);else set.remove(a.info.packageName);prefs.edit().putStringSet("bypassApps",set).apply();updatePending();if(selectedOnly)filter();});CheckBox check=h.check;convert.setOnClickListener(v->check.setChecked(!check.isChecked()));return convert;}
    }
    private static final class AppHolder {ImageView icon;TextView name,pkg;CheckBox check;}
    private void rulePage(){
        LinearLayout head=card("让规则保持新鲜",updateSummary());LinearLayout metrics=row();metric(metrics,format(rules==null?0:rules.count()),"当前有效域名");metric(metrics,format(rules==null?0:rules.userList(true).size()),"手动放行域名");gap(head,15);head.addView(metrics);addButton(head,"更新已启用订阅",true,()->work("下载并校验规则",()->{return rules.updateRules(ruleTarget())?"所有启用来源已校验并整批更新":"规则内容没有变化，保留原规则与回滚快照";},this::loadStatus));
        if(!prefs.getString("dailyUpdateError","").isEmpty()){gap(head,10);head.addView(text(prefs.getString("dailyUpdateError",""),12,ERROR,false));}
        LinearLayout profiles=card("保护档位",rules==null?"加载中":("当前："+rules.profileTitle()+" · 切换不会删除黑白名单"));
        actionRow(profiles,"shield","选择轻量 / 均衡 / 加强","整批切换来源，不自动开启隐私跟踪列表",this::showProfiles);
        LinearLayout aliases=card("DNS 别名保护","仅应用保护模式有效；系统 hosts 模式不检查 DNS 响应。");
        toggle(aliases,"检查 CNAME 别名链",prefs.getBoolean("cnameProtection",false),on->{prefs.edit().putBoolean("cnameProtection",on).apply();message(on?"已开启别名链检查；对随后处理的响应和缓存生效":"已关闭别名链检查");});
        aliases.addView(text("发现别名指向已拦截域名时阻断。误拦可在活动里查看目标，放行原查询名可豁免该查询的整条链。默认关闭。",11,MUTED,false));
        section("规则来源");LinearLayout sources=card(null,null);if(rules==null)sources.addView(text("正在加载规则来源…",13,MUTED,false));else try{JSONArray list=rules.sources();for(int n=0;n<list.length();n++){JSONObject source=list.getJSONObject(n);String id=source.getString("id");LinearLayout r=row();r.setPadding(0,dp(11),0,dp(11));LinearLayout labels=column();labels.addView(text(source.optString("name",id),14,TEXT,true));gap(labels,6);long count=source.optLong("count",-1);labels.addView(text(count<0?"使用模块合并规则":format(count)+" 条来源规则",11,MUTED,false));labels.setOnClickListener(v->showLong(source.optString("name",id),source.optString("url")));r.addView(labels,new LinearLayout.LayoutParams(0,-2,1));Switch sw=new Switch(this);sw.setThumbTintList(ColorStateList.valueOf(SURFACE));sw.setTrackTintList(new ColorStateList(new int[][]{new int[]{android.R.attr.state_checked},new int[]{}},new int[]{ACCENT,LINE}));sw.setChecked(source.optBoolean("enabled"));sw.setContentDescription("启用 "+source.optString("name",id));sw.setOnCheckedChangeListener((b,on)->{if(busy){b.setOnCheckedChangeListener(null);b.setChecked(!on);return;}work("切换规则来源",()->{rules.setSource(id,on,ruleTarget());return "来源设置已更新";},this::loadStatus);});r.addView(sw);sources.addView(r);if(n+1<list.length())divider(sources);}}catch(Exception e){sources.addView(text("读取来源失败："+e.getMessage(),12,ERROR,false));}
        section("例外与排查");LinearLayout lists=card(null,null);actionRow(lists,"search","检查误拦域名","输入网址，查看命中来源并直接放行",this::showTroubleshooter);divider(lists);actionRow(lists,"check","白名单",rules==null?"加载中":rules.userList(true).size()+" 个域名 · 优先放行",()->showList(true));divider(lists);actionRow(lists,"shield","黑名单",rules==null?"加载中":rules.userList(false).size()+" 个域名 · 手动拦截",()->showList(false));
        LinearLayout maintenance=card(null,null);toggle(maintenance,"每日自动更新",prefs.getBoolean("dailyUpdateEnabled",false),on->{UpdateJobService.schedule(this,on);String e=prefs.getString("dailyUpdateError","");if(!e.isEmpty())message(e);});maintenance.addView(text("网络可用时执行；系统省电策略可能推迟更新。",11,MUTED,false));gap(maintenance,7);divider(maintenance);actionRow(maintenance,"clock","恢复上一份规则","更新误拦时可回退",()->new AlertDialog.Builder(this).setTitle("恢复上一份规则？").setMessage("将回退到上一份完整规则快照。").setNegativeButton("取消",null).setPositiveButton("恢复",(d,n)->work("恢复规则",()->{rules.rollback(ruleTarget());return "已恢复上一份完整规则";},this::loadStatus)).show());divider(maintenance);actionRow(maintenance,"download","名单导入与导出","备份域名、订阅与应用放行设置",this::showBackup);
    }
    private void showProfiles(){
        String[] ids={"lite","balanced","enhanced"};
        String[] labels={"轻量 · 秋风纯广告","均衡 · 秋风 + AdAway","加强 · 均衡 + HaGeZi Light"};
        new AlertDialog.Builder(this).setTitle("选择保护档位").setItems(labels,(dialog,which)->
            new AlertDialog.Builder(this).setTitle("应用"+RuleProfiles.title(ids[which])+"档位？")
                .setMessage("保留手动黑白名单和模块暂停状态；整批调整订阅。隐私跟踪源会关闭，可之后手动开启。加强规则更广，但可能增加误拦；可恢复上一份规则。")
                .setNegativeButton("取消",null).setPositiveButton("应用",(d,n)->work("切换保护档位",()->{
                    rules.setProfile(ids[which],ruleTarget());return "已整批应用"+RuleProfiles.title(ids[which])+"档位";
                },this::loadStatus)).show()).setNegativeButton("取消",null).show();
    }
    private void showTroubleshooter(){LinearLayout c=column();c.addView(text("误拦排查",22,TEXT,true));gap(c,10);c.addView(text("输入域名或网址，检查当前规则。此操作不会访问网址；规则命中不等于真实请求已被拦截。",12,MUTED,false));EditText entry=input("例如 ads.example.com");c.addView(entry);final Dialog dialog=sheet(c);addButton(c,"检查当前规则",true,()->{String d=RuleStore.normalize(entry.getText().toString());if(d==null){entry.setError("请输入有效域名或 HTTP(S) 网址");return;}dialog.dismiss();work("检查域名",()->installed()?domainReport(d):rules.describe(d),()->{});});actionRow(c,"check","加入白名单","此域名对所有应用放行",()->domainFromEntry(entry,true,dialog));actionRow(c,"shield","加入黑名单","此域名对所有应用拦截",()->domainFromEntry(entry,false,dialog));divider(c);actionRow(c,"activity","从最近请求里定位","开启请求记录后，可点击域名放行",()->{dialog.dismiss();tab=3;showPage(false);renderNav();});}
    private void domainFromEntry(EditText e,boolean allow,Dialog dialog){String d=RuleStore.normalize(e.getText().toString());if(d==null){e.setError("请输入有效域名");return;}dialog.dismiss();changeDomain(d,allow,true);}
    private void changeDomain(String domain,boolean allow,boolean add){work("更新域名名单",()->{rules.changeDomain(domain,allow,add,ruleTarget());return domain+" 已"+(add?"加入":"移出")+(allow?"白名单":"黑名单");},this::loadStatus);}
    private String domainReport(String domain)throws Exception{RootBridge.Result r=RootBridge.run(this,"check-domain",domain);checked(r);JSONObject j=new JSONObject(r.output);StringBuilder b=new StringBuilder(domain).append("\n\n").append(j.optBoolean("allowed")?"白名单优先放行":j.optBoolean("blocked")?"命中当前有效拦截规则":"未命中当前有效规则");JSONArray matches=j.optJSONArray("matches");if(matches!=null&&matches.length()>0){b.append("\n\n命中来源");for(int n=0;n<matches.length();n++){JSONObject m=matches.getJSONObject(n);b.append("\n• ").append(m.optString("name",m.optString("id"))).append(m.optBoolean("enabled")?"":"（已停用）");}}return b.append("\n\n").append(vpn()?"当前为应用保护，以实际 DNS 请求为准":j.optBoolean("mounted")?"hosts 已验证挂载":"hosts 尚未验证生效").toString();}
    private void showList(boolean allow){if(rules==null)return;List<String> list=rules.userList(allow);LinearLayout c=column();c.addView(text(allow?"域名白名单":"域名黑名单",22,TEXT,true));gap(c,9);c.addView(text("点击域名可移除。"+(allow?"白名单始终优先放行。":"只有确切域名匹配时拦截。"),12,MUTED,false));final Dialog d=sheet(c);EditText search=input("搜索域名");c.addView(search);LinearLayout items=column();c.addView(items);java.util.function.Consumer<String> filter=q->{items.removeAllViews();int n=0;for(String domain:list){if(!domain.contains(q.toLowerCase(Locale.ROOT)))continue;if(n++>=80)break;TextView line=text(domain,13,TEXT,false);line.setPadding(dp(8),dp(15),dp(8),dp(15));line.setBackground(tappable(Color.TRANSPARENT,10));line.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("移除此域名？").setMessage(domain).setNegativeButton("取消",null).setPositiveButton("移除",(x,y)->{d.dismiss();changeDomain(domain,allow,false);}).show());items.addView(line);}if(n==0)items.addView(text("暂无匹配域名",13,MUTED,false));if(n>80)items.addView(text("请搜索以定位其余域名",12,MUTED,false));};watch(search,filter);filter.accept("");}
    private void showBackup(){LinearLayout c=column();c.addView(text("名单备份",22,TEXT,true));gap(c,10);c.addView(text("导入或导出域名名单、订阅选择和应用放行名单，不包含请求记录。",12,MUTED,false));final Dialog d=sheet(c);actionRow(c,"download","导出名单 JSON","保存到你选择的位置",()->{d.dismiss();exportFile("settings");});actionRow(c,"rules","导入名单 JSON","恢复先前保存的名单",()->{d.dismiss();Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("application/json");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,IMPORT);});}
    private void activityPage(){
        LinearLayout page=column();page.setPadding(dp(19),dp(3),dp(19),0);content.addView(page,new FrameLayout.LayoutParams(-1,-1));LinearLayout stats=card(page);stats.setPadding(dp(17),dp(16),dp(17),dp(16));LinearLayout metrics=row();queryMetric=metric(metrics,format(prefs.getLong("queries",0)),"DNS 请求");blockMetric=metric(metrics,format(prefs.getLong("blocked",0)),"已拦截");errorMetric=metric(metrics,format(prefs.getLong("errors",0)),"解析错误");stats.addView(metrics);gap(stats,13);divider(stats);toggle(stats,"记录最近 100 条 DNS 请求",prefs.getBoolean("requestLogs",false),on->{DnsVpnService.setRequestLogging(this,on);if(logAdapter!=null)logAdapter.refresh();});stats.addView(text(vpn()?"只记录本机域名，不记录网页内容。请求无法可靠归属到具体应用。":"以下为历史应用保护数据；模块模式不能统计真实请求。",11,MUTED,false));
        EditText search=input("搜索请求域名");search.setText(logSearch);page.addView(search);watch(search,s->{logSearch=s;if(logAdapter!=null)logAdapter.refresh();});
        LinearLayout actions=row();TextView tip=text("最近请求 · 点击域名可放行",11,MUTED,false);actions.addView(tip,new LinearLayout.LayoutParams(0,dp(36),1));TextView clear=text("清空",12,ACCENT,true);clear.setPadding(dp(13),dp(11),0,dp(11));clear.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("清空请求记录？").setMessage("仅清除本机最近域名记录，累计统计保留。").setNegativeButton("取消",null).setPositiveButton("清空",(d,n)->{DnsVpnService.clearRequestLogs(this);if(logAdapter!=null)logAdapter.refresh();}).show());actions.addView(clear);page.addView(actions);
        FrameLayout holder=new FrameLayout(this);holder.setBackground(background(SURFACE,22));TextView empty=text("",13,MUTED,false);empty.setGravity(Gravity.CENTER);pad(empty,23);holder.addView(empty,new FrameLayout.LayoutParams(-1,-1));logList=new ListView(this);logList.setDivider(new ColorDrawable(LINE));logList.setDividerHeight(dp(1));logList.setPadding(dp(15),0,dp(15),0);logList.setVerticalScrollBarEnabled(false);logList.setEmptyView(empty);holder.addView(logList,new FrameLayout.LayoutParams(-1,-1));page.addView(holder,new LinearLayout.LayoutParams(-1,0,1));logAdapter=new LogAdapter(empty);logList.setAdapter(logAdapter);logList.setOnItemClickListener((p,v,n,id)->showDomainAction(logAdapter.shown.get(n)));logAdapter.refresh();
    }
    private final class LogAdapter extends BaseAdapter {
        final ArrayList<JSONObject> shown=new ArrayList<>();final TextView empty;
        LogAdapter(TextView e){empty=e;}
        void refresh(){int position=logList==null?0:logList.getFirstVisiblePosition();int offset=logList==null||logList.getChildCount()==0?0:logList.getChildAt(0).getTop();shown.clear();try{JSONArray logs=new JSONArray(prefs.getString("dnsLogs","[]"));String q=logSearch.toLowerCase(Locale.ROOT).trim();for(int n=logs.length()-1;n>=0;n--){JSONObject entry=logs.optJSONObject(n);if(entry!=null&&(entry.optString("domain")+" "+entry.optString("matchedDomain")).toLowerCase(Locale.ROOT).contains(q))shown.add(entry);}}catch(Exception ignored){}empty.setText(!logSearch.trim().isEmpty()?"没有匹配的请求":prefs.getBoolean("requestLogs",false)?"还没有请求记录\n开启应用保护并使用应用后，会在这里显示":"请求记录未开启\n打开上方开关后，记录仅保存在本机");notifyDataSetChanged();if(logList!=null&&position>0)logList.setSelectionFromTop(position,offset);}
        public int getCount(){return shown.size();}public Object getItem(int n){return shown.get(n);}public long getItemId(int n){return n;}
        public View getView(int n,View convert,ViewGroup parent){LogHolder h;if(convert==null){h=new LogHolder();LinearLayout r=column();r.setPadding(0,dp(15),0,dp(15));LinearLayout top=row();h.domain=text("",13,TEXT,true);h.domain.setSingleLine(true);h.domain.setEllipsize(TextUtils.TruncateAt.MIDDLE);top.addView(h.domain,new LinearLayout.LayoutParams(0,-2,1));h.result=text("",10,ACCENT,true);h.result.setPadding(dp(8),dp(5),dp(8),dp(5));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-2,-2);rp.leftMargin=dp(10);top.addView(h.result,rp);r.addView(top);gap(r,7);h.time=text("",10,MUTED,false);r.addView(h.time);r.setTag(h);convert=r;}else h=(LogHolder)convert.getTag();JSONObject entry=shown.get(n);String result=entry.optString("result");h.domain.setText(entry.optString("domain","未知域名"));h.result.setText(outcome(result));boolean blocked=result.equals("blocked")||result.equals("blocked_cname"),error=isDnsError(result);h.result.setTextColor(blocked||error?ERROR:ACCENT);h.result.setBackground(background(blocked||error?(dark?0xff3d3028:0xfff7eae1):SOFT,9));h.time.setText(dateTime(entry.optLong("time"))+(entry.optString("matchedDomain").isEmpty()?"":" · 目标 "+entry.optString("matchedDomain")));return convert;}
    }
    private static final class LogHolder {TextView domain,result,time;}
    private boolean isDnsError(String s){return !Arrays.asList("allowed","blocked","blocked_cname","cached","fallback").contains(s);}
    private String outcome(String s){switch(s){case "blocked":return "已拦截";case "blocked_cname":return "别名拦截";case "allowed":return "已放行";case "cached":return "缓存命中";case "fallback":return "备用解析";case "upstream_error":return "上游错误";case "timeout":return "解析超时";case "offline":return "等待网络";case "network_changed":return "网络切换";case "busy":return "请求繁忙";case "invalid_response":return "响应异常";default:return "解析失败";}}
    private void showDomainAction(JSONObject item){String domain=RuleStore.normalize(item.optString("domain"));if(domain==null)return;LinearLayout c=column();c.addView(text(domain,20,TEXT,true));gap(c,10);c.addView(text(dateTime(item.optLong("time"))+" · "+outcome(item.optString("result")),12,MUTED,false));final Dialog d=sheet(c);String alias=RuleStore.normalize(item.optString("matchedDomain"));if(alias!=null){c.addView(text("命中别名目标："+alias+"\n放行原查询名只豁免该查询的链；放行目标域名会影响其他查询。",12,ERROR,false));actionRow(c,"search","检查别名目标来源",alias,()->{d.dismiss();work("检查别名",()->installed()?domainReport(alias):rules.describe(alias),()->{});});divider(c);}actionRow(c,"check","放行此域名","加入全局白名单，之后的匹配请求放行",()->{d.dismiss();changeDomain(domain,true,true);});divider(c);actionRow(c,"search","检查命中来源","查看此域名为什么被拦截",()->{d.dismiss();work("检查域名",()->installed()?domainReport(domain):rules.describe(domain),()->{});});divider(c);actionRow(c,"shield","拦截此域名","加入全局黑名单",()->{d.dismiss();changeDomain(domain,false,true);});actionRow(c,"info","复制域名",null,()->{copy("域名",domain);Toast.makeText(this,"域名已复制",Toast.LENGTH_SHORT).show();});}
    private void showSettings(){
        LinearLayout c=column();c.addView(text("设置与诊断",22,TEXT,true));gap(c,10);c.addView(text("辟尘 "+version(),12,MUTED,false));final Dialog dialog=sheet(c);
        actionRow(c,"settings","外观",new String[]{"跟随系统","浅色","深色"}[prefs.getString("appearance","system").equals("light")?1:prefs.getString("appearance","system").equals("dark")?2:0],()->{dialog.dismiss();showAppearance();});divider(c);actionRow(c,"activity","DNS 解析设置",prefs.getString("dnsTransport","udp").equals("doh")?"加密 DNS · HTTPS":"普通 DNS · "+prefs.getString("upstream","223.5.5.5"),()->{dialog.dismiss();showDnsSettings();});divider(c);actionRow(c,"info","运行健康检查","逐项检查挂载、完整性与冲突",()->{dialog.dismiss();runDiagnostics();});divider(c);actionRow(c,"clock","模块操作日志","安装、应用与更新的实际记录",()->{dialog.dismiss();work("读取模块日志",()->checked(RootBridge.run(this,"logs")),()->{});});divider(c);actionRow(c,"refresh","刷新模块状态","重新读取 Root 和规则状态",()->{dialog.dismiss();loadStatus();});divider(c);
        toggle(c,"重启后恢复应用保护",prefs.getBoolean("autoStartVpn",false),on->prefs.edit().putBoolean("autoStartVpn",on).apply());c.addView(text("仅恢复你已授权且主动开启的应用保护。",11,MUTED,false));gap(c,13);divider(c);actionRow(c,"module","模块管理","安装内置模块或导出 ZIP",()->{dialog.dismiss();showModuleManager();});divider(c);actionRow(c,"download","导出诊断信息","保存可读状态与操作结果",()->{dialog.dismiss();exportText=diagnosticSummary()+"\n\n最近操作\n"+notice;exportFile("diagnostics");});divider(c);actionRow(c,"info","关于辟尘","工作范围、隐私与开源许可",()->{dialog.dismiss();showLong("关于辟尘","辟尘 "+version()+"\nGPL-3.0-or-later\n\n广告与追踪域名过滤，由你决定例外。\n\n模块模式不占用 VPN；应用保护使用本地 DNS VPN。不会安装根证书，不解密网页内容。开启请求记录后，仅在本机记录最近域名。\n\n域名过滤无法保证去除同域名广告、应用内置素材、开屏倒计时或空白占位。私人 DNS、应用自带 DoH 或代理远端解析可能绕过过滤。\n\n构建验证不代表 HyperOS／Android 16 真机验证。各方案比较与来源许可见随附源码。" );});
    }
    private void showAppearance(){String[] values={"system","light","dark"};String selected=prefs.getString("appearance","system");int n=Arrays.asList(values).indexOf(selected);new AlertDialog.Builder(this).setTitle("外观").setSingleChoiceItems(new String[]{"跟随系统","浅色","深色"},Math.max(0,n),(d,which)->{prefs.edit().putString("appearance",values[which]).apply();d.dismiss();if(useDark()!=dark)recreate();}).setNegativeButton("取消",null).show();}
    private void showDnsSettings(){LinearLayout c=column();c.addView(text("DNS 解析",22,TEXT,true));gap(c,10);c.addView(text("仅用于应用保护。保存后，正在运行的应用保护会重新建立。",12,MUTED,false));final Dialog dialog=sheet(c);String current=prefs.getString("dnsTransport","udp");RadioGroup transports=new RadioGroup(this);transports.setOrientation(LinearLayout.HORIZONTAL);RadioButton udp=radio("普通 DNS",101,current.equals("udp")),doh=radio("加密 HTTPS",102,current.equals("doh"));transports.addView(udp,new RadioGroup.LayoutParams(0,dp(52),1));transports.addView(doh,new RadioGroup.LayoutParams(0,dp(52),1));c.addView(transports);
        EditText server=input("数字 IP，例如 223.5.5.5");server.setText(prefs.getString("upstream","223.5.5.5"));c.addView(server);LinearLayout providers=column();providers.addView(text("加密 DNS 提供商",12,MUTED,true));Spinner provider=new Spinner(this);ArrayAdapter<String> adapter=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Cloudflare","Google"});provider.setAdapter(adapter);provider.setSelection(prefs.getString("dohProvider","cloudflare").equals("google")?1:0);providers.addView(provider,new LinearLayout.LayoutParams(-1,dp(50)));c.addView(providers);server.setVisibility(doh.isChecked()?View.GONE:View.VISIBLE);providers.setVisibility(doh.isChecked()?View.VISIBLE:View.GONE);transports.setOnCheckedChangeListener((g,id)->{server.setVisibility(id==102?View.GONE:View.VISIBLE);providers.setVisibility(id==102?View.VISIBLE:View.GONE);});
        gap(c,8);c.addView(text("加密模式使用标准解析服务，备用上游仍为 HTTPS。应用自带的加密 DNS 不会被此设置接管。",11,MUTED,false));addButton(c,"保存解析设置",true,()->{String ip=server.getText().toString().trim();if(!doh.isChecked())try{DnsVpnService.numericAddress(ip);}catch(Exception e){server.setError("请输入有效 DNS 数字 IP");return;}SharedPreferences.Editor edit=prefs.edit().putString("dnsTransport",doh.isChecked()?"doh":"udp").putString("dohProvider",provider.getSelectedItemPosition()==1?"google":"cloudflare");if(!doh.isChecked())edit.putString("upstream",ip);edit.apply();dialog.dismiss();if(vpn())restartVpn();else message("DNS 设置已保存，下次开启应用保护生效");});
        gap(c,14);divider(c);long latency=prefs.getLong("dnsLatencyMs",0);c.addView(text(networkSummary()+"\n近期解析耗时  "+(latency>0?latency+" ms":"暂无数据")+"\n缓存命中  "+format(prefs.getLong("cacheHits",0))+"\n备用解析  "+format(prefs.getLong("dnsFallbackCount",0)),12,MUTED,false));String report=prefs.getString("dnsNetworkReportError","");if(vpn()&&!report.isEmpty())c.addView(text(report,12,ERROR,false));String e=prefs.getString("dnsLastError","");if(!e.isEmpty()){gap(c,10);c.addView(text("最近解析错误："+e,12,ERROR,false));}actionRow(c,"settings","系统私人 DNS 设置",null,()->{try{startActivity(new Intent("android.settings.PRIVATE_DNS_SETTINGS"));}catch(Exception e2){startActivity(new Intent(Settings.ACTION_WIRELESS_SETTINGS));}});
    }
    private RadioButton radio(String label,int id,boolean checked){RadioButton r=new RadioButton(this);r.setId(id);r.setText(label);r.setTextColor(TEXT);r.setTextSize(12);r.setButtonTintList(ColorStateList.valueOf(ACCENT));r.setChecked(checked);return r;}
    private void runDiagnostics(){if(pendingReboot()){showLong("等待重启","模块更新已安装。请先重启手机，完成模块加载后再运行健康检查。");return;}work("检查模块健康状态",()->{String command=status.optString("capabilities").contains("health")?"health":"diagnose";return checked(RootBridge.run(this,command));},()->{});}
    private String diagnosticSummary(){return "辟尘 "+version()+"\n检查时间："+dateTime(System.currentTimeMillis())+"\n模块版本："+status.optString("version","未知")+"\n模块已安装："+(installed()?"是":"未确认")+"\n等待重启："+(pendingReboot()?"是":"否")+"\n规则已启用："+(status.optBoolean("enabled")?"是":"否")+"\n实际挂载已验证："+(status.optBoolean("mounted")?"是":"否")+"\n有效模块规则："+format(status.optLong("ruleCount"))+"\n数据占用："+bytes(status.optLong("storageBytes"))+"\n应用保护运行："+(vpn()?"是":"否")+"\n上游网络状态："+networkSummary()+"\n上游网络报告："+prefs.getString("dnsNetworkReportError","无错误记录")+"\n已放行应用："+prefs.getInt("activeBypassCount",0)+"\n最近错误："+prefs.getString("vpnError",status.optString("error","无"))+"\n\n模块详情\n"+humanJson(status);}
    private void toggle(LinearLayout l,String label,boolean value,Flag action){Switch sw=new Switch(this);sw.setText(label);sw.setTextColor(TEXT);sw.setTextSize(13);sw.setPadding(0,dp(12),0,dp(12));sw.setMinimumHeight(dp(49));sw.setThumbTintList(ColorStateList.valueOf(SURFACE));sw.setTrackTintList(new ColorStateList(new int[][]{new int[]{android.R.attr.state_checked},new int[]{}},new int[]{ACCENT,LINE}));sw.setChecked(value);sw.setOnCheckedChangeListener((v,on)->action.changed(on));l.addView(sw,new LinearLayout.LayoutParams(-1,-2));}
    private EditText input(String hint){EditText e=new EditText(this);e.setHint(hint);e.setHintTextColor(MUTED);e.setTextSize(13);e.setTextColor(TEXT);e.setSingleLine(true);e.setPadding(dp(15),dp(14),dp(15),dp(14));e.setBackground(background(SOFT,16));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(49));p.topMargin=dp(10);p.bottomMargin=dp(7);e.setLayoutParams(p);return e;}
    private void watch(EditText e,java.util.function.Consumer<String> callback){e.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int before,int c){callback.accept(s.toString());}public void afterTextChanged(Editable value){}});}
    private Dialog sheet(LinearLayout contents){Dialog dialog=new Dialog(this);LinearLayout root=column();root.setPadding(dp(23),dp(11),dp(23),dp(24));root.setBackground(background(SURFACE,29));View handle=new View(this);handle.setBackground(background(LINE,3));LinearLayout.LayoutParams hp=new LinearLayout.LayoutParams(dp(34),dp(4));hp.gravity=Gravity.CENTER;hp.bottomMargin=dp(21);root.addView(handle,hp);ScrollView sc=new ScrollView(this);sc.setFillViewport(false);sc.setVerticalScrollBarEnabled(false);sc.addView(contents);root.addView(sc,new LinearLayout.LayoutParams(-1,-2));dialog.setContentView(root);Window w=dialog.getWindow();if(w!=null){w.setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));w.addFlags(WindowManager.LayoutParams.FLAG_DIM_BEHIND);WindowManager.LayoutParams attrs=w.getAttributes();attrs.gravity=Gravity.BOTTOM;attrs.dimAmount=.3f;w.setAttributes(attrs);w.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);}dialog.show();if(w!=null){int height=getResources().getDisplayMetrics().heightPixels;w.setLayout(-1,-2);root.post(()->{if(root.getHeight()>height*.87f)w.setLayout(-1,(int)(height*.87f));});}return dialog;}
    private void showLong(String title,String value){LinearLayout c=column();c.addView(text(title,21,TEXT,true));gap(c,15);TextView t=text(value==null?"没有内容":value,13,TEXT,false);t.setTextIsSelectable(true);c.addView(t);final Dialog d=sheet(c);LinearLayout pair=row();pair.setPadding(0,dp(16),0,0);TextView copy=button("复制",false,()->{copy(title,value);Toast.makeText(this,"已复制",Toast.LENGTH_SHORT).show();});LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(0,-2,1);cp.rightMargin=dp(9);pair.addView(copy,cp);pair.addView(button("导出",false,()->{d.dismiss();exportText=title+"\n\n"+value;exportFile("diagnostics");}),new LinearLayout.LayoutParams(0,-2,1));c.addView(pair);}
    private void copy(String title,String value){android.content.ClipboardManager c=(android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE);c.setPrimaryClip(ClipData.newPlainText(title,value));}
    private String checked(RootBridge.Result r)throws Exception{JSONObject j;try{j=new JSONObject(r.output);}catch(Exception e){if(r.code!=0)throw new IOException(r.output);return r.output;}if(r.code!=0||!j.optBoolean("ok",false))throw new IOException(j.optString("message",j.optString("error",humanJson(j))));return j.has("checks")||j.has("lines")?humanJson(j):j.has("message")?j.getString("message"):humanJson(j);}
    private String humanJson(JSONObject j){JSONArray checks=j.optJSONArray("checks");if(checks!=null){StringBuilder b=new StringBuilder(j.optBoolean("healthy",true)?"模块健康检查完成":"发现需要处理的问题");for(int i=0;i<checks.length();i++){JSONObject c=checks.optJSONObject(i);if(c==null)continue;b.append("\n\n").append(c.optBoolean("passed")?"通过 · ":"需处理 · ").append(c.optString("title",c.optString("id"))).append("\n").append(c.optString("detail"));}JSONArray warnings=j.optJSONArray("warnings");if(warnings!=null&&warnings.length()>0){b.append("\n\n提示");for(int i=0;i<warnings.length();i++)b.append("\n").append(warnings.optString(i));}return b.toString();}StringBuilder b=new StringBuilder();Iterator<String> keys=j.keys();while(keys.hasNext()){String k=keys.next();Object v=j.opt(k);if(k.equals("ok"))continue;if(v instanceof JSONArray){JSONArray list=(JSONArray)v;if(list.length()==0)continue;b.append(label(k)).append("\n");for(int i=0;i<list.length();i++){Object item=list.opt(i);b.append(item instanceof JSONObject?humanJson((JSONObject)item):String.valueOf(item)).append("\n");}}else if(v instanceof JSONObject)b.append(label(k)).append("\n").append(humanJson((JSONObject)v));else b.append(label(k)).append("：").append(v instanceof Boolean?((Boolean)v?"是":"否"):String.valueOf(v)).append("\n");}return b.toString().trim();}
    private String label(String k){String[] keys={"version","enabled","mounted","ruleCount","hostsBytes","storageBytes","updatedAt","allowCount","blockCount","conflicts","warnings","sources","lines","checks","capabilities","configRevision","hasBackup","installed","engine","name","id","count","url","message","error","framework","pendingReboot","details"};String[] values={"模块版本","规则已启用","挂载已验证","有效规则","规则文件字节","存储字节","更新时间","白名单数量","黑名单数量","冲突","提示","规则来源","检查记录","检查项目","支持能力","规则版本","存在备份","模块已安装","过滤方式","名称","标识","规则数量","订阅地址","结果","错误","Root 框架","等待重启","详情"};for(int i=0;i<keys.length;i++)if(keys[i].equals(k))return values[i];return k;}
    private boolean pendingReboot(){return status.optBoolean("pendingReboot",false);}
    private void loadStatus(){if(busy)return;work("检查模块与规则",()->{if(rules==null)rules=new RuleStore(this);bundledModuleVersion=ModuleInstaller.bundledInfo(this).optString("version","");status=RootBridge.status(this);statusLoaded=true;if(installed()&&modern()&&!pendingReboot())rules.syncFromModule();else if(!pendingReboot())rules.reload();return pendingReboot()?"模块更新已安装，请重启手机后再操作保护与规则。":"";},()->{});}
    private void rootCommand(String command){if(pendingReboot()){message("模块更新等待重启，请先重启手机。");return;}if(vpnEngaged()&&!command.equals("pause")){message("请先停止应用保护并完成恢复，再启用模块保护。");return;}if(!installed()){message("模块尚未确认安装，请先安装内置模块并重启，或检查 Root 授权。");return;}work("更新保护状态",()->checked(RootBridge.run(this,command)),this::loadStatus);}
    private void work(String label,Job job,Runnable after){if(busy||destroyed)return;busy=true;busyLabel=label;updateBanner();worker.execute(()->{String result;boolean success=false;try{result=job.run();success=true;}catch(Exception e){result=e.getMessage()==null?e.toString():e.getMessage();}final String output=result;final boolean ok=success;ui.post(()->{if(destroyed)return;busy=false;notice=output;updateBanner();if(tab==0||tab==2)showPage(true);else if(tab==1)updatePending();else if(logAdapter!=null)logAdapter.refresh();if(!output.isEmpty()&&(output.length()>170||output.contains("\n\n")||label.equals("检查域名")))showLong(ok?label+"结果":"操作未完成",output);if(ok)after.run();drainDocumentResult();});});}
    private void message(String s){notice=s==null?"操作失败":s;updateBanner();}
    private void prepareVpn(){if(busy)return;if(pendingReboot()){message("模块更新等待重启，重启后再开启应用保护。");return;}new AlertDialog.Builder(this).setTitle("开启应用保护？").setMessage("将启动本地 DNS VPN，暂停辟尘 hosts 模块，使所选应用可以放行。不能与另一个 VPN 同时使用；应用自带 DoH、私人 DNS 或直连 IP 可能绕过过滤。停止后会尝试恢复原模块状态。").setNegativeButton("取消",null).setPositiveButton("开启",(d,n)->work("准备应用保护",()->{status=RootBridge.status(this);if(pendingReboot())throw new IOException("请先重启手机完成模块更新");if(!status.optBoolean("ok",false))throw new IOException(status.optString("error",status.optString("message","无法确认模块状态，请先授权 Root")));if(installed()){if(!modern())throw new IOException("请先安装内置新版模块并重启。");rules.syncFromModule();}else rules.reload();return "";},()->{Intent request=VpnService.prepare(this);if(request!=null)startActivityForResult(request,VPN_REQUEST);else startVpn();})).show();}
    private void startVpn(){prefs.edit().putString("preferredMode","vpn").putBoolean("vpnWanted",true).apply();if(Build.VERSION.SDK_INT>=33&&checkSelfPermission("android.permission.POST_NOTIFICATIONS")!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{"android.permission.POST_NOTIFICATIONS"},80);try{startForegroundService(new Intent(this,DnsVpnService.class).setAction(DnsVpnService.ACTION_START));message("正在启动应用保护，等待实际运行状态。");monitorVpn(true,0);}catch(Exception e){message("应用保护未启动："+e.getMessage());}}
    private void stopVpn(){try{startForegroundService(new Intent(this,DnsVpnService.class).setAction(DnsVpnService.ACTION_STOP));message("正在停止应用保护，并恢复原模块状态…");monitorVpn(false,0);}catch(Exception e){message("未能发送停止请求："+e.getMessage());}}
    private void restartVpn(){if(pendingReboot()){message("模块更新等待重启，重启后再重新建立应用保护。");return;}try{startForegroundService(new Intent(this,DnsVpnService.class).setAction(DnsVpnService.ACTION_RESTART));message("正在重新建立应用保护，更改将在成功后生效。");monitorVpn(true,0);}catch(Exception e){message("未能重新建立保护："+e.getMessage());}}
    private void monitorVpn(boolean expected,int attempt){ui.postDelayed(()->{if(destroyed)return;String e=prefs.getString("vpnError","");if(!e.isEmpty()&&attempt>0){message(e);if(tab==0)showPage(true);return;}boolean done=expected?vpn():!vpn()&&!prefs.getBoolean("vpnRestoreHosts",false)&&!prefs.getBoolean("vpnWanted",false);if(done&&attempt>0){message(expected?"应用保护正在运行，请查看实际放行状态。":"应用保护已停止，正在读取模块状态。 ");if(tab==0)showPage(true);updatePending();loadStatus();}else if(attempt<15)monitorVpn(expected,attempt+1);else{message("保护切换尚未确认，请在设置中刷新状态查看具体结果。");if(tab==0)showPage(true);}},600);}
    private void exportFile(String kind){if(kind.equals("module")&&bundledModuleVersion.isEmpty()){message("模块信息尚未校验完成，请先刷新状态");return;}pendingExport=kind;Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType(kind.equals("module")?"application/zip":kind.equals("diagnostics")?"text/plain":"application/json");i.putExtra(Intent.EXTRA_TITLE,kind.equals("module")?"Bichen-"+bundledModuleVersion+"-module.zip":kind.equals("diagnostics")?"Bichen-diagnostics.txt":"Bichen-domain-lists.json");startActivityForResult(i,EXPORT);}
    @Override protected void onActivityResult(int request,int result,Intent data) {
        super.onActivityResult(request,result,data);
        if(request==VPN_REQUEST){if(result==RESULT_OK)startVpn();else message("未授予 VPN 权限，保护方式未切换。");return;}
        if(result!=RESULT_OK||data==null||data.getData()==null)return;
        if(request!=EXPORT&&request!=IMPORT)return;
        queuedDocumentRequest=request;queuedDocumentUri=data.getData().toString();
        queuedDocumentKind=pendingExport;queuedDocumentText=exportText;
        drainDocumentResult();
    }
    /** SAF results must survive recreation and must never be discarded by the busy guard. */
    private void drainDocumentResult() {
        if(busy||destroyed||queuedDocumentUri.isEmpty())return;
        final int request=queuedDocumentRequest;
        final android.net.Uri uri=android.net.Uri.parse(queuedDocumentUri);
        final String kind=queuedDocumentKind,report=queuedDocumentText;
        queuedDocumentUri="";queuedDocumentKind="";queuedDocumentText="";queuedDocumentRequest=0;
        if(request==EXPORT){
            if(!Arrays.asList("module","settings","diagnostics").contains(kind)){
                message("导出类型未能恢复，请重新选择导出项目；未向文件写入错误内容。");return;
            }
            work("导出文件",()->{
                try(OutputStream out=getContentResolver().openOutputStream(uri,"wt")){
                    if(out==null)throw new IOException("无法打开目标文件");
                    if(kind.equals("module")){
                        try(InputStream in=new FileInputStream(ModuleInstaller.bundledZip(this))){
                            byte[] bytes=new byte[16384];int n;while((n=in.read(bytes))>=0)out.write(bytes,0,n);
                        }
                    }else if(kind.equals("diagnostics"))out.write(report.getBytes(StandardCharsets.UTF_8));
                    else out.write(rules.exportSettings().toString(2).getBytes(StandardCharsets.UTF_8));
                }
                return "文件已导出";
            },()->{});
        }else if(request==IMPORT){
            work("导入名单",()->{
                ByteArrayOutputStream out=new ByteArrayOutputStream();
                try(InputStream in=getContentResolver().openInputStream(uri)){
                    if(in==null)throw new IOException("无法读取文件");
                    byte[] bytes=new byte[8192];int n;
                    while((n=in.read(bytes))>=0){if(out.size()+n>32*1024*1024)throw new IOException("名单文件超过 32 MB");out.write(bytes,0,n);}
                }
                rules.importSettings(new JSONObject(out.toString("UTF-8")),ruleTarget());
                return "名单已导入；应用排除更改需重新建立应用保护。";
            },this::loadStatus);
        }
    }
    private String version(){try{return getPackageManager().getPackageInfo(getPackageName(),0).versionName;}catch(Exception e){return "0.3.0-beta.1";}}
    private String date(long t){return new SimpleDateFormat("M月d日 HH:mm",Locale.CHINA).format(new Date(t));}
    private String dateTime(long t){return t<=0?"时间未知":new SimpleDateFormat("M月d日 HH:mm:ss",Locale.CHINA).format(new Date(t));}
    private String format(long value){return NumberFormat.getIntegerInstance(Locale.CHINA).format(value);}
    private String bytes(long value){return value<1024?value+" B":value<1048576?String.format(Locale.ROOT,"%.1f KB",value/1024.0):String.format(Locale.ROOT,"%.2f MB",value/1048576.0);}
}
